### ISSUE TITLE
Group project kanban board set up

### ISSUE THREAD

**Issue by HERMON-1995** [HERMON-1995/space-travelers-hub-group-project#25]
**In this project we are 2 of us. We have assigned ourselves cards from the kanban board. And this is our Github project url [Project](https://github.com/HERMON-1995/space-travelers-hub-group-project/projects/1).**

**Comment by pinkmoon25** [comment]
Hi @HERMON-1995 @Newtayo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/N6YkmfQBeEEjLDcoDl/giphy.gif"/>

## Highlights
Kanban setup :heavy_check_mark: 
Tasks Assigned fairly :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HERMON-1995** [comment]
Thank you for approving the setup of kanban board! 😊
